[package]
name = "msm-rtsp-stub"
version = "0.0.1"
authors = ["Giles Heron <giheron@cisco.com>"]
description = "RTSP Sidecar Stub Proxy written in Rust"
repository = "https://github.com/media-streaming-mesh/msm-rtsp-stub"
readme = "README.md"
keywords = ["RTSP"]
license = "Apache 2.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }