@Library(['srePipeline']) _

// --------------------------------------------
// Refer to Pipeline docs for options used in mysettings
// https://wwwin-github.cisco.com/pages/eti/sre-pipeline-library
// --------------------------------------------

def pipelinesettings = [
  deploy: [
    [name: "msm_rtsp_stub" ]        // Containers to publish
  ],

  tagversion: "${env.BUILD_ID}",    // Docker tag version
  prepare: 1,                       // GIT Clone
  build: 1,                         // Build container
  publishContainer: 1,              // Publish container
  ecr: 1,                           // Publish container to Private ECR
  gitDefaultBranch: "main",         // Default Git Branch
  disableInclusiveLint:1,           // Disable disableInclusiveLint during development
]

srePipeline( pipelinesettings )
