name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: beta
            components: rustfmt, rust-std, clippy

      - name: Set up protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: cargo test --verbose
